name: Maven Central Repo Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check out Git repository
        uses: actions/checkout@v3
      # https://github.com/actions/setup-java
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
          server-id: oss
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - id: install-secret-key
        name: Install Gpg Secret Key
        run: | 
          cat <(echo -e "${{ secrets.OSS_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish Package
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: mvn clean deploy -P release -Dgpg.passphrase=${{ secrets.OSS_GPG_SECRET_KEY_PASSWORD }}